/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;

namespace TeleKinesisNet
{

  public partial class CollectorPayload : TBase
  {
    private string _schema;
    private string _ipAddress;
    private long _timestamp;
    private string _encoding;
    private string _collector;
    private string _userAgent;
    private string _refererUri;
    private string _path;
    private string _querystring;
    private string _body;
    private List<string> _headers;
    private string _contentType;
    private string _hostname;
    private string _networkUserId;

    public string Schema
    {
      get
      {
        return _schema;
      }
      set
      {
        __isset.schema = true;
        this._schema = value;
      }
    }

    public string IpAddress
    {
      get
      {
        return _ipAddress;
      }
      set
      {
        __isset.ipAddress = true;
        this._ipAddress = value;
      }
    }

    public long Timestamp
    {
      get
      {
        return _timestamp;
      }
      set
      {
        __isset.timestamp = true;
        this._timestamp = value;
      }
    }

    public string Encoding
    {
      get
      {
        return _encoding;
      }
      set
      {
        __isset.encoding = true;
        this._encoding = value;
      }
    }

    public string Collector
    {
      get
      {
        return _collector;
      }
      set
      {
        __isset.collector = true;
        this._collector = value;
      }
    }

    public string UserAgent
    {
      get
      {
        return _userAgent;
      }
      set
      {
        __isset.userAgent = true;
        this._userAgent = value;
      }
    }

    public string RefererUri
    {
      get
      {
        return _refererUri;
      }
      set
      {
        __isset.refererUri = true;
        this._refererUri = value;
      }
    }

    public string Path
    {
      get
      {
        return _path;
      }
      set
      {
        __isset.path = true;
        this._path = value;
      }
    }

    public string Querystring
    {
      get
      {
        return _querystring;
      }
      set
      {
        __isset.querystring = true;
        this._querystring = value;
      }
    }

    public string Body
    {
      get
      {
        return _body;
      }
      set
      {
        __isset.body = true;
        this._body = value;
      }
    }

    public List<string> Headers
    {
      get
      {
        return _headers;
      }
      set
      {
        __isset.headers = true;
        this._headers = value;
      }
    }

    public string ContentType
    {
      get
      {
        return _contentType;
      }
      set
      {
        __isset.contentType = true;
        this._contentType = value;
      }
    }

    public string Hostname
    {
      get
      {
        return _hostname;
      }
      set
      {
        __isset.hostname = true;
        this._hostname = value;
      }
    }

    public string NetworkUserId
    {
      get
      {
        return _networkUserId;
      }
      set
      {
        __isset.networkUserId = true;
        this._networkUserId = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool schema;
      public bool ipAddress;
      public bool timestamp;
      public bool encoding;
      public bool collector;
      public bool userAgent;
      public bool refererUri;
      public bool path;
      public bool querystring;
      public bool body;
      public bool headers;
      public bool contentType;
      public bool hostname;
      public bool networkUserId;
    }

    public CollectorPayload()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 31337:
              if (field.Type == TType.String)
              {
                Schema = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 100:
              if (field.Type == TType.String)
              {
                IpAddress = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 200:
              if (field.Type == TType.I64)
              {
                Timestamp = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 210:
              if (field.Type == TType.String)
              {
                Encoding = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 220:
              if (field.Type == TType.String)
              {
                Collector = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 300:
              if (field.Type == TType.String)
              {
                UserAgent = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 310:
              if (field.Type == TType.String)
              {
                RefererUri = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 320:
              if (field.Type == TType.String)
              {
                Path = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 330:
              if (field.Type == TType.String)
              {
                Querystring = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 340:
              if (field.Type == TType.String)
              {
                Body = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 350:
              if (field.Type == TType.List)
              {
                {
                  Headers = new List<string>();
                  TList _list0 = await iprot.ReadListBeginAsync(cancellationToken);
                  for(int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    string _elem2;
                    _elem2 = await iprot.ReadStringAsync(cancellationToken);
                    Headers.Add(_elem2);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 360:
              if (field.Type == TType.String)
              {
                ContentType = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 400:
              if (field.Type == TType.String)
              {
                Hostname = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 410:
              if (field.Type == TType.String)
              {
                NetworkUserId = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("CollectorPayload");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (IpAddress != null && __isset.ipAddress)
        {
          field.Name = "ipAddress";
          field.Type = TType.String;
          field.ID = 100;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(IpAddress, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.timestamp)
        {
          field.Name = "timestamp";
          field.Type = TType.I64;
          field.ID = 200;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI64Async(Timestamp, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Encoding != null && __isset.encoding)
        {
          field.Name = "encoding";
          field.Type = TType.String;
          field.ID = 210;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(Encoding, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Collector != null && __isset.collector)
        {
          field.Name = "collector";
          field.Type = TType.String;
          field.ID = 220;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(Collector, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (UserAgent != null && __isset.userAgent)
        {
          field.Name = "userAgent";
          field.Type = TType.String;
          field.ID = 300;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(UserAgent, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (RefererUri != null && __isset.refererUri)
        {
          field.Name = "refererUri";
          field.Type = TType.String;
          field.ID = 310;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(RefererUri, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Path != null && __isset.path)
        {
          field.Name = "path";
          field.Type = TType.String;
          field.ID = 320;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(Path, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Querystring != null && __isset.querystring)
        {
          field.Name = "querystring";
          field.Type = TType.String;
          field.ID = 330;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(Querystring, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Body != null && __isset.body)
        {
          field.Name = "body";
          field.Type = TType.String;
          field.ID = 340;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(Body, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Headers != null && __isset.headers)
        {
          field.Name = "headers";
          field.Type = TType.List;
          field.ID = 350;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          {
            await oprot.WriteListBeginAsync(new TList(TType.String, Headers.Count), cancellationToken);
            foreach (string _iter3 in Headers)
            {
              await oprot.WriteStringAsync(_iter3, cancellationToken);
            }
            await oprot.WriteListEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (ContentType != null && __isset.contentType)
        {
          field.Name = "contentType";
          field.Type = TType.String;
          field.ID = 360;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(ContentType, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Hostname != null && __isset.hostname)
        {
          field.Name = "hostname";
          field.Type = TType.String;
          field.ID = 400;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(Hostname, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (NetworkUserId != null && __isset.networkUserId)
        {
          field.Name = "networkUserId";
          field.Type = TType.String;
          field.ID = 410;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(NetworkUserId, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Schema != null && __isset.schema)
        {
          field.Name = "schema";
          field.Type = TType.String;
          field.ID = 31337;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(Schema, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString()
    {
      var sb = new StringBuilder("CollectorPayload(");
      bool __first = true;
      if (Schema != null && __isset.schema)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Schema: ");
        sb.Append(Schema);
      }
      if (IpAddress != null && __isset.ipAddress)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("IpAddress: ");
        sb.Append(IpAddress);
      }
      if (__isset.timestamp)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Timestamp: ");
        sb.Append(Timestamp);
      }
      if (Encoding != null && __isset.encoding)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Encoding: ");
        sb.Append(Encoding);
      }
      if (Collector != null && __isset.collector)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Collector: ");
        sb.Append(Collector);
      }
      if (UserAgent != null && __isset.userAgent)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("UserAgent: ");
        sb.Append(UserAgent);
      }
      if (RefererUri != null && __isset.refererUri)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("RefererUri: ");
        sb.Append(RefererUri);
      }
      if (Path != null && __isset.path)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Path: ");
        sb.Append(Path);
      }
      if (Querystring != null && __isset.querystring)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Querystring: ");
        sb.Append(Querystring);
      }
      if (Body != null && __isset.body)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Body: ");
        sb.Append(Body);
      }
      if (Headers != null && __isset.headers)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Headers: ");
        sb.Append(Headers);
      }
      if (ContentType != null && __isset.contentType)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("ContentType: ");
        sb.Append(ContentType);
      }
      if (Hostname != null && __isset.hostname)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Hostname: ");
        sb.Append(Hostname);
      }
      if (NetworkUserId != null && __isset.networkUserId)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("NetworkUserId: ");
        sb.Append(NetworkUserId);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
